procs:
  ---- vS-Graphs ----:
    shell: ""
    autostart: false
  vS-Graphs RGBD:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
      source ~/workspace/install/setup.bash &&
      ros2 launch vs_graphs rgbd.launch.py"'
    autostart: false
  vS-Graphs RGBD-IMU:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
      source ~/workspace/install/setup.bash &&
      ros2 launch vs_graphs rgbd-imu.launch.py"'
    autostart: false
  vS-Graphs RGBD Live:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
      source ~/workspace/install/setup.bash &&
      ros2 launch vs_graphs rgbd.launch.py offline:=false rgb_image_topic:=/camera/camera/color/image_raw
      depth_image_topic:=/camera/camera/aligned_depth_to_color/image_raw rgb_camera_info_topic:=/camera/camera/color/camera_info"'
    autostart: false
  vS-Graphs RGBD-IMU Live:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
      source ~/workspace/install/setup.bash &&
      ros2 launch vs_graphs rgbd-imu.launch.py offline:=false rgb_image_topic:=/camera/camera/color/image_raw imu_topic:=/camera/camera/imu
      depth_image_topic:=/camera/camera/aligned_depth_to_color/image_raw rgb_camera_info_topic:=/camera/camera/color/camera_info"'
    autostart: false
  Baseline RGBD:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
      source ~/workspace/install/setup.bash &&
      ros2 launch vs_graphs rgbd.launch.py semantic_scene_segmenter:=off"'
    autostart: false

  -- Custom vS-Graphs --:
    shell: ""
    autostart: false
  vS-Graphs AutoSense:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
      source ~/workspace/install/setup.bash &&
      ros2 launch vs_graphs rgbd.launch.py sensor_config:=SMapper_RealSense rgb_image_topic:=/camera/camera/color/image_raw
      depth_image_topic:=/camera/camera/aligned_depth_to_color/image_raw rgb_camera_info_topic:=/camera/camera/color/camera_info"'
    autostart: false
  vS-Graphs ICL:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
      source ~/workspace/install/setup.bash &&
      ros2 launch vs_graphs rgbd.launch.py sensor_config:=ICL rgb_image_topic:=/camera/color/image_raw
      depth_image_topic:=/camera/depth/image_raw rgb_camera_info_topic:=/camera/color/camera_info"'
    autostart: false
  vS-Graphs OpenLoris:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
      source ~/workspace/install/setup.bash &&
      ros2 launch vs_graphs rgbd.launch.py sensor_config:=OpenLorisScene rgb_image_topic:=/d400/color/image_raw
      depth_image_topic:=/d400/aligned_depth_to_color/image_raw rgb_camera_info_topic:=/d400/color/camera_info camera_frame:=d400_color"'
    autostart: false
  vS-Graphs TUM-RGBD:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
      source ~/workspace/install/setup.bash &&
      ros2 launch vs_graphs rgbd.launch.py rgb_image_topic:=/camera/rgb/image_color depth_image_topic:=/camera/depth/image
      rgb_camera_info_topic:=/camera/rgb/camera_info sensor_config:=TUM3 camera_frame:=kinect"'
    autostart: false
  vS-Graphs ScanNet:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
      source ~/workspace/install/setup.bash &&
      ros2 launch vs_graphs rgbd.launch.py sensor_config:=ScanNet depth_image_topic:=/camera/depth/image_raw
      rgb_image_topic:=/camera/color/image_raw rgb_camera_info_topic:=/camera/color/camera_info"'
    autostart: false

  ---- Procedures ----:
    shell: ""
    autostart: false
  Build vS-Graphs:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
      source ~/workspace/install/setup.bash && cd ~/workspace &&
      colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-select vs_graphs"'
    autostart: false
  Build SemSeg:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
      source ~/workspace/install/setup.bash && cd ~/workspace &&
      colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-select segmenter_ros"'
    autostart: false
  Build RealSense:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
      source ~/workspace/install/setup.bash && cd ~/workspace &&
      colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-select realsense-ros"'
    autostart: false

  # ---- Tools ----:
  #   shell: ''
  #   autostart: false
  # Voxblox Client:
  #   shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
  #     python ~/workspace/vsgraphs_tools/relay_jazzy.py --mode voxblox_client"'
  #   autostart: false
  # PointCloud Server:
  #   shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
  #     python ~/workspace/vsgraphs_tools/relay_jazzy.py --mode pc_server"'
  #   autostart: false

  ---- Sensors ----:
    shell: ""
    autostart: false
  RealSense RGBD:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
      source ~/workspace/install/setup.bash &&
      ros2 launch realsense2_camera rs_launch.py pointcloud.enable:=true align_depth.enable:=true
      rgb_camera.color_profile:="640,480,30" depth_camera.depth_profile:="640,480,30""'
    autostart: false
  RealSense RGBD-IMU:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
      source ~/workspace/install/setup.bash &&
      ros2 launch realsense2_camera rs_launch.py pointcloud.enable:=true align_depth.enable:=true
      rgb_camera.color_profile:="640,480,30" depth_camera.depth_profile:="640,480,30"
      enable_accel:=true enable_gyro:=true gyro_fps:=200 accel_fps:=63 unite_imu_method:=0"'
    autostart: false

  ---- Evaluation ----:
    shell: ""
    autostart: false
  Gen. KF Poses:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash &&
      python ~/workspace/src/visual_sgraphs/evaluation/generate_kf_pose_txt_files.py"'
    autostart: false
